### ISSUE TITLE
Create a Symfony Bundle

### ISSUE THREAD

**Issue by jderusse** [async-aws/aws#145]
provides:
- semantic configuration (covers client's Configuration options)
- autowiring

**Comment by Nyholm** [comment]
A symfony bridge like a bundle?

**Comment by jderusse** [comment]
yes indeed, title updated

**Comment by Nyholm** [comment]
Suggestion: 

The configuration could look like this: 

```yaml
async_aws:
  default: # Will be merged with other configuration
    config:
      region: eu-central-1
  sqs:
    config:
        region: us-west-1
  sns: ~ # This will complain if we dont have that package installed
```

I can get a service called `AsyncAws\S3\S3Client`. I've never configured it, but it used the default config.

----------

I dont think we should support multiple types of `S3Clients`. You have to register your own services if you want more than one.
