### ISSUE TITLE
SSM parameter + env processor

### ISSUE THREAD

**Issue by Nemo64** [async-aws/aws#486]
I'd love to be able to read ssm parameter using this library.

Actually I want to build a symfony bundle that allows me to read secret parameters using EnvProcessors like this:
```php
services:
    some_service:
        arguments: ['%env(ssm:/path/to/parameter)%']
```
This is especially interesting with secret parameters. Maybe even with the secret manager.

- I either build everything with the aws-sdk
- I could contribute here and try to add ssm parameter support (but not the entire ssm api, that's a lot)
- Or I could contribute ssm parameter support and maybe even build ssm env processors into the symfony bundle.

**Comment by jderusse** [comment]
Oh I love this idea!!! definitively something to add in the bundle!

**Comment by jderusse** [comment]
note: this is not necessary to crate an env processor (you'll have some issue with `/` in path).
We can use an EnvVarLoaderInterface for that.

```
services:
    some_service:
        arguments: ['%env(MY_SECRET)%']
   AsyncAws\SymfonyBundle\SsmEnvVarLoader:
       arguments:
         $path: /path/to/parameters/root
```
