### ISSUE TITLE
Php session handler

### ISSUE THREAD

**Issue by Nemo64** [async-aws/aws#527]
The aws sdk comes with a [session handler](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/service_dynamodb-session-handler.html) that stores session data in dynamodb.
Since the [session handler interface](https://www.php.net/manual/en/class.sessionhandlerinterface.php) is a native php feature, this could probably be a feature of async-aws as well.

The aws/sdk session handler can easily be integrated in symfony as well.
```yaml
framework:
    session:
        handler_id: session.handler.dynamodb

services:
    session.handler.dynamodb:
        class: Aws\DynamoDb\SessionHandler
        factory: [Aws\DynamoDb\SessionHandler, fromClient]
        arguments:
            - '@aws.dynamodb'
            - {table_name: '%env(resolve:SESSION_TABLE)%'}
```

But maybe there is some room for optimisation with the async-aws bundle as well although documenting it is probably enough.
