### ISSUE TITLE
[DynamoDB] Allow custom local endpoint

### ISSUE THREAD

**Issue by akira28** [async-aws/aws#702]
I'm trying to use a different endpoint for my local DynamoDB docker `http://dynamo:8000` but the endpoint for the `local` region is hardcoded to `http://localhost:8000`.

Also, it should work with any credentials, but I'm getting: 
```
Request must contain either a valid (registered) AWS access key ID or X.509 certificate.
```

**Comment by jderusse** [comment]
Yes, the region `local` is hardcoded by AWS. See https://github.com/aws/aws-sdk-php/blob/master/src/data/endpoints.json#L1765-L1771

Did you tried configuring the `endpoint` parameter? and ignoring the region?

**Comment by akira28** [comment]
Yes, I tried setting an endpoint, and without setting a region. It still defaults to `http://localhost:8000`

And if I hardcode `http://dynamo:8000` in the library, i get the `Request must contain either a valid (registered) AWS access key ID or X.509 certificate.` error

**Comment by jderusse** [comment]
Could you please share your code? I can't reproduce it
```php
$client = new DynamoDbClient(['endpoint' => 'http://dynamo:8000']);
$client->getItem(['TableName' => 'test'])->resolve();
```
Which calls `http://dynamo:8000` in my case....

**Comment by akira28** [comment]
Your approach works, but is it possible to not use real AWS auth keys? Without keys I'm getting auth error.

Also, the symfony bundle seems to not take in consideration the endpoint config when set in the async_aws.yml file

**Comment by tyx** [comment]
> Your approach works, but is it possible to not use real AWS auth keys? Without keys I'm getting auth error.

On my side, I'm using empty keys in this case !

> Also, the symfony bundle seems to not take in consideration the endpoint config when set in the async_aws.yml file

Could you share your yaml file ? I'm using this endpoint config and it works pretty well

**Comment by akira28** [comment]
> > Your approach works, but is it possible to not use real AWS auth keys? Without keys I'm getting auth error.
> 
> On my side, I'm using empty keys in this case !

hehehe I didn't try with empty keys, how silly of me
But I had to pass everything to the client:

```
        $dynamoDb = new DynamoDbClient([
            'endpoint' => 'http://dynamo:8000',
            'accessKeyId' => '',
            'accessKeySecret' => ''
        ]);
```
because this bundle config does not have any effect:
```
async_aws:
    config:
        region: '%env(AWS_REGION)%'
        accessKeyId: '%env(AWS_KEY)%'
        accessKeySecret: '%env(AWS_SECRET)%'
    clients:
        dynamo_db:
            config:
                endpoint: '%env(DYNAMODB_ENDPOINT)%'
```

.env:
```
###> async-aws/async-aws-bundle ###
AWS_KEY=
AWS_SECRET=
AWS_REGION=eu-west-1
DYNAMODB_ENDPOINT=http://dynamo:8000
###< async-aws/async-aws-bundle ###
```

**Comment by tyx** [comment]
your config looks good.

But if you using symfony bundle, we are ok you should use directly services provided by the bundle. In your case:
`async_aws.client.dynamo_db` (or via autowire of course)

**Comment by jderusse** [comment]
did you try:
```
async_aws:
    clients:
        dynamo_db:
            config:
                endpoint: '%env(DYNAMODB_ENDPOINT)%'
````

or
```
async_aws:
    config:
        region: '%env(AWS_REGION)%'
        accessKeyId: '%env(AWS_KEY)%'
        accessKeySecret: '%env(AWS_SECRET)%'
    clients:
        dynamo_db:
            config:
                endpoint: '%env(DYNAMODB_ENDPOINT)%'
                accessKeyId: ~
                accessKeySecret: ~
```
