### ISSUE TITLE
[Symfony] Multiple AWS clients

### ISSUE THREAD

**Issue by derrabus** [async-aws/aws#908]
The Symfony bundle allows me to configure my AWS clients like this:

```YAML
async_aws:
    clients:
        s3:
            config:
                # insert S3 configuration here
```

This format assumes that I use the same AWS credentials for all S3 buckets I want to access. However, in my application, this is not the case. I need to access two different S3 buckets in different regions with different credentials. Right now, I need to configure one of the clients manually.

It would be awesome, if the bundle would allow me to configure multiple AWS clients.

**Comment by jderusse** [comment]
did you tried?
```yaml
async_aws:
    clients:
        foo:
            type: s3
        bar:
            type: s3
```
